# Installs oracle Java on the agent
---


- name: "[JAVA] OSX installation tasks"
  include_tasks: bambooagent_install_java_osx.yml
  when: ansible_distribution=='MacOSX'

- name: "[JAVA] Ubuntu installation tasks"
  include_tasks: bambooagent_install_java_linux.yml
  when: ansible_distribution=="Ubuntu"

- name: "[JAVA] Windows installation tasks"
  include_tasks: bambooagent_install_java_win.yml
  when: ansible_os_family=="Windows"
