#
# Ubuntu
#

- block:

  - name: '[JAVA] create destination path'
    file:
      path: "{{ java_installation_path }}"
      state: directory

  - name: '[JAVA] copy installer'
    copy:
      src: "{{ java_installation.file }}"
      dest: "/tmp/{{ java_installation.file | basename }}"

  - name: '[JAVA] deflate installer'
    unarchive:
      src: "/tmp/{{ java_installation.file | basename }}"
      dest: "{{ java_installation_path }}"
      remote_src: yes

  - name: '[JAVA] update alternatives for java'
    shell: |
      update-alternatives --install "/usr/bin/{{ item }}" "{{ item }}" "{{ java_installation_path }}/{{ java_installation.folder }}/bin/{{ item }}" 1
      chmod a+x /usr/bin/{{ item }}
      update-alternatives --set {{ item }} {{ java_installation_path }}/{{ java_installation.folder }}/bin/{{ item }}
    loop:
      - "java"
      - "javac"
      - "javaws"

  - name: '[JAVA] check java'
    command: java -version

  - name: Advertising the JAVA_HOME and JAVA_BIN
    set_fact:
      JAVA_HOME: "{{ java_installation_path }}/{{ java_installation.folder }}"
      JAVA_BIN: "{{ java_installation_path }}/{{ java_installation.folder }}/bin/java"
      cacheable: true

  when: ansible_distribution == "Ubuntu"

# Installing the certificate
- block:

  - name: '[JAVA] check keytool'
    shell: PATH=$(dirname $(readlink -f $(which java))):$PATH keytool -help

  - name: '[JAVA] list existing certificates'
    shell: >
      PATH=$(dirname $(readlink -f $(which java))):$PATH
      keytool -list -keystore {{ java_installation_path }}/{{ java_installation.folder }}/{{ java_keystore_location }} -storepass changeit
    register: java_certificates

  - name: '[JAVA] transfer the certificate'
    copy:
      src={{ item.file }}
      dest=/tmp/{{ item.file | basename }}
    loop: "{{ certificate_files }}"
    when: item.alias not in java_certificates.stdout

  - name: '[JAVA] install certificates into the Java keystore'
    shell: >
      PATH=$(dirname $(readlink -f $(which java))):$PATH
      keytool -import -trustcacerts -keystore {{ java_installation_path }}/{{ java_installation.folder }}/{{ java_keystore_location }}
      -storepass changeit -noprompt -alias {{ item.alias }} -file "/tmp/{{ item.file | basename }}"
    loop: "{{ certificate_files }}"
    when: item.alias not in java_certificates.stdout

  when: ansible_distribution=="Ubuntu"

  always:
    - name: '[JAVA] cleaning certificates'
      file:
        path: "/tmp/{{ item.file | basename }}"
        state: absent
      loop: "{{ certificate_files }}"
